version: "3.9"

services:

  database-service:
    image: mysql:5.7
    container_name: desafio-database
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
      MYSQL_USER: desafio
      MYSQL_PASSWORD: desafio
    volumes:
      - db-volume:/var/lib/mysql
    
  api-service:
    build: .
    container_name: desafio-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
    links:
      - database-service
    depends_on:
      - database-service

volumes:
  db-volume:
    driver: local


